// Generated by scripts/build-ai-context.mjs on every build. Do not edit.

const CONTEXT = {
  "generatedAt": "2026-10-04T22:50:54.329Z",
  "person": {
    "name": "Emmanuel Moghalu",
    "role": "Software & Data Engineer",
    "location": "Abuja, Nigeria",
    "timezone": "UTC+1",
    "availability": "open to full-time roles and contract work, remote or hybrid, open to relocation",
    "email": "emma.moghalu@gmail.com",
    "links": {
      "github": "https://github.com/emmanuelrichard01",
      "linkedin": "https://www.linkedin.com/in/e-mc/",
      "x": "https://x.com/mrebr",
      "site": "https://www.builtbyem.dev"
    },
    "focus": [
      "event-driven data pipelines",
      "payment reconciliation and multi-PSP integration",
      "stream processing",
      "analytics warehouses",
      "Nigerian fintech (CBN, NDPR compliance)"
    ]
  },
  "counts": {
    "builtSystems": 11,
    "designStudies": 2,
    "caseStudies": 10,
    "roles": 7
  },
  "projects": [
    {
      "id": "vega-canva",
      "title": "Vega Studio",
      "subtitle": "Real-Time Collaborative Infinite Canvas",
      "tier": "flagship",
      "category": "Realtime Collaboration",
      "timeline": "2026",
      "status": "live",
      "stack": [
        "TypeScript",
        "React",
        "Konva",
        "Yjs",
        "Hocuspocus",
        "Node.js",
        "PostgreSQL",
        "Redis",
        "S3",
        "Docker"
      ],
      "metrics": [
        "Automated Tests: 4,076",
        "Move @500 Objects: ~5.7ms",
        "Chart Kinds: 30"
      ],
      "summary": "It started as a two-day Vega IT hackathon brief: a real-time shared canvas with no edges. Rooms are shared by link, the board has to stay smooth past 100 objects, it needs text, shapes, images, sticky notes and voice notes, and guests join without signing up. The harder problem sits underneath. On a board with no edges, people are rarely looking at the same spot, so the interface has to show where everyone is and what they are doing without getting in the way of the work. The network will also drop, so editing has to keep working without a server and come back together afterwards without anyone losing work. After the hackathon the project was rebuilt to a stricter standard than the brief asked for.",
      "hasCaseStudy": true,
      "tradeoffCount": 5,
      "tradeoffs": [
        {
          "decision": "How edits are synced",
          "chose": "A CRDT (Yjs) with no central server deciding the order",
          "rejected": "A server that orders every edit (operational transform)",
          "why": "With no central authority, every copy of the board settles on the same result by itself. That is exactly what makes offline editing work: changes made while disconnected merge in when you reconnect, instead of being rejected by a server that has moved on."
        },
        {
          "decision": "Diagrams written as text",
          "chose": "Convert Mermaid into the canvas's own shapes",
          "rejected": "Render it with the mermaid package",
          "why": "The package produces one SVG picture, which can't be edited on a board where the whole point is that everything can be, and it weighs over a megabyte. Converting into the canvas's own shapes means every box and arrow can be moved, restyled and exported again."
        },
        {
          "decision": "Resizing",
          "chose": "Resize an invisible stand-in, then redraw objects at the new size",
          "rejected": "Stretch the objects themselves (Konva scaleX / scaleY)",
          "why": "Stretching is the wrong action for almost everything here. A stretched sticky note has stretched padding and blurry text, and a stretched line has a thicker stroke. The gesture records the new size outside React, and each object draws itself at that size."
        },
        {
          "decision": "Who runs the physics",
          "chose": "One person's browser owns each moving object",
          "rejected": "Every browser simulates every object",
          "why": "Two separate simulations land the same object in slightly different places and then fight over where it is. One owner runs the simulation and saves the result, and everyone else plays back the owner's path."
        },
        {
          "decision": "Gravity",
          "chose": "Force as something you aim: pull, push, drop, wind, shockwave",
          "rejected": "Constant gravity across the whole board",
          "why": "A board with no edges has no floor. Constant gravity would pull everything off the board forever, and nothing would ever come to rest."
        }
      ],
      "links": {
        "github": "https://github.com/emmanuelrichard01/vega-canva",
        "live": "https://vscanva.vercel.app"
      }
    },
    {
      "id": "mmr-engine",
      "title": "MMR Engine",
      "subtitle": "PSP-to-Ledger Payment Reconciliation",
      "tier": "flagship",
      "category": "Fintech Core System",
      "timeline": "2026",
      "status": "source available",
      "stack": [
        "Python",
        "FastAPI",
        "PostgreSQL",
        "Redpanda",
        "Prefect",
        "MinIO",
        "Next.js",
        "Prometheus",
        "Grafana",
        "Docker"
      ],
      "metrics": [
        "Automated Tests: 276",
        "Against Real Postgres: 23",
        "Reversible Migrations: 16"
      ],
      "summary": "A Nigerian business that collects money on Paystack and pays out on Flutterwave gets two records of every movement of money, and they don't always agree. Settlements go missing, amounts differ, the same event arrives twice, and notifications (webhooks) arrive out of order or not at all. Someone in finance then finds the gaps by hand in a spreadsheet. Automating that is easy to demo and hard to trust. A tool that drops a notification during an outage, matches one payment twice, or quietly guesses between two equally good candidates produces numbers that are worse than the spreadsheet's, because they look certain.",
      "hasCaseStudy": true,
      "tradeoffCount": 5,
      "tradeoffs": [
        {
          "decision": "How each event is guaranteed to land once",
          "chose": "Accept repeats and make them harmless: at-least-once delivery, 'seen' keys and a database uniqueness rule",
          "rejected": "Relying on the queue's 'exactly-once' promise",
          "why": "Exactly-once can't be guaranteed end to end across a web request, a queue and a database. Accepting that events may arrive twice, and making the second arrival do nothing, gets the result that matters (each event lands once) from promises each part can actually keep."
        },
        {
          "decision": "Matching people's names",
          "chose": "Keyed tokens, one per word of the name",
          "rejected": "Comparing masked names letter by letter (trigram similarity)",
          "why": "Masking throws away exactly what matching needs. 'Chioma Okonkwo' and 'Chisom Onyekwe' both mask to 'C***** O******' and scored as a perfect match. Tokens still match when words are swapped, titles added or a middle name dropped, and no plain-text name is needed to match (ADR 0001)."
        },
        {
          "decision": "Two equally good candidates",
          "chose": "Leave the payment unmatched for review, with the evidence",
          "rejected": "Take the first or highest-scoring candidate",
          "why": "A wrong automatic match costs more than a manual review, because it hides a real problem behind a confident-looking pair."
        },
        {
          "decision": "Message queue",
          "chose": "Redpanda",
          "rejected": "Apache Kafka",
          "why": "It speaks the Kafka API from a single program with no ZooKeeper to run, which matters for a reference stack meant to run on one machine."
        },
        {
          "decision": "How the console reaches the API",
          "chose": "Through its own server, which only passes on an approved list of routes",
          "rejected": "Calling the API from the browser with a key",
          "why": "Any key the browser holds is a key every visitor holds. The console's server adds the key itself, only passes on read and resolve requests, and rejects writes from other websites."
        }
      ],
      "links": {
        "github": "https://github.com/emmanuelrichard01/mmr-engine"
      }
    },
    {
      "id": "logistics-watchtower",
      "title": "Logistics Watchtower",
      "subtitle": "Real-Time Cold Chain Fleet Monitoring",
      "tier": "flagship",
      "category": "Real-Time Systems",
      "timeline": "2026",
      "status": "source available",
      "stack": [
        "Python",
        "FastAPI",
        "Redpanda",
        "Quix Streams",
        "Docker",
        "Prometheus"
      ],
      "metrics": [
        "Latency: <200ms",
        "Sensors: 15+/truck",
        "Alert Rules: 8"
      ],
      "summary": "Cold chain deliveries fail when cargo drifts out of its safe temperature range. Most monitoring only looks at the data after the trip, so a temperature problem shows up after delivery, when the cargo is already lost. The information is accurate, and too late to be useful.",
      "hasCaseStudy": true,
      "tradeoffCount": 4,
      "tradeoffs": [
        {
          "decision": "Message broker",
          "chose": "Redpanda",
          "rejected": "Apache Kafka",
          "why": "Written in C++, it has no Java pauses, and dropping ZooKeeper removes something else to run. The cost is a younger ecosystem."
        },
        {
          "decision": "Stream processing",
          "chose": "Quix Streams",
          "rejected": "Spark / Flink",
          "why": "Plain Python and lightweight, which suits a job that needs speed but little computing power. It gives up large-scale scaling that this problem doesn't need."
        },
        {
          "decision": "Getting updates to the dashboard",
          "chose": "WebSocket",
          "rejected": "Asking the server every few seconds (REST polling)",
          "why": "A live fleet map needs updates in under a second. Polling adds delay and server load and still gives a worse result."
        },
        {
          "decision": "Where alert state lives",
          "chose": "In memory",
          "rejected": "A database",
          "why": "It is lost on restart, and that is named as a demo-scope choice, not defended. Production would use Redis or Kafka Streams state stores."
        }
      ],
      "links": {
        "github": "https://github.com/emmanuelrichard01/logistics-watchtower"
      }
    },
    {
      "id": "modern-warehouse",
      "title": "Modern Data Warehouse",
      "subtitle": "1.5M+ Record Analytics Platform",
      "tier": "flagship",
      "category": "Analytics Engineering",
      "timeline": "2025",
      "status": "source available",
      "stack": [
        "Python",
        "Dagster",
        "dbt",
        "DuckDB",
        "Docker",
        "Plotly"
      ],
      "metrics": [
        "Records: 1.5M+",
        "dbt Tests: 21",
        "Coverage: 80%+"
      ],
      "summary": "The Olist Brazilian e-commerce dataset comes as nine separate files (orders, payments, reviews, sellers, locations and more) with nothing tying them together. Most people load a convenient slice and stop there. Any question that crosses those files needs a real warehouse behind it.",
      "hasCaseStudy": true,
      "tradeoffCount": 1,
      "tradeoffs": [
        {
          "decision": "Storage engine",
          "chose": "DuckDB",
          "rejected": "PostgreSQL",
          "why": "The work is analysis (totals and groupings across whole tables), not lots of small updates. A built-in analytics engine (OLAP) is far faster here and leaves no server to run."
        }
      ],
      "links": {
        "github": "https://github.com/emmanuelrichard01/modern-warehouse"
      }
    },
    {
      "id": "medvax",
      "title": "MedVax",
      "subtitle": "Health-Tech Telemedicine & E-Commerce",
      "tier": "production",
      "category": "Health-Tech Platform",
      "timeline": "Jan – Feb 2026",
      "status": "live",
      "stack": [
        "NestJS",
        "Next.js",
        "PostgreSQL",
        "Redis",
        "BullMQ",
        "Paystack",
        "WhatsApp API"
      ],
      "metrics": [
        "Stack: NestJS + Next.js",
        "Auth: JWT + RBAC",
        "Status: Production"
      ],
      "summary": "Getting sexual and reproductive health products in West Africa runs into two problems at once: privacy and supply. People who need contraceptives, prescription medicine or a frank conversation with a clinician often won't walk into a pharmacy and ask. And the pharmacies that do stock what they need are independent shops with no shared stock list or way of fulfilling orders together.",
      "hasCaseStudy": true,
      "tradeoffCount": 3,
      "tradeoffs": [
        {
          "decision": "Second way in",
          "chose": "A WhatsApp assistant",
          "rejected": "A mobile app",
          "why": "The people this serves already have WhatsApp and already treat it as private. An app is another install and another icon on the home screen, and for private health needs that icon itself gives something away."
        },
        {
          "decision": "What the assistant may do",
          "chose": "Help people find the next step and route them, nothing more",
          "rejected": "Letting the AI answer clinical questions",
          "why": "An AI that names a medicine has effectively prescribed it. The assistant is kept away from that and books a consultation instead."
        },
        {
          "decision": "Assigning deliveries",
          "chose": "Manual, or the nearest pharmacy",
          "rejected": "A third-party delivery service",
          "why": "A deliberate cut for the first version. Connecting a delivery service waits until the order flow itself is proven to work."
        }
      ],
      "links": {
        "live": "https://medvaxhealth.com"
      }
    },
    {
      "id": "ultra-news",
      "title": "ULTRA-NEWS V3",
      "subtitle": "The Wire Room",
      "tier": "production",
      "category": "News Intelligence",
      "timeline": "2025 – Present",
      "status": "live",
      "stack": [
        "Python",
        "Django",
        "Next.js",
        "TypeScript",
        "PostgreSQL",
        "pgvector",
        "Celery",
        "Redis"
      ],
      "metrics": [
        "Corroboration: Publishers",
        "Ingestion: 41 Feeds",
        "Tests: 180"
      ],
      "summary": "When something happens, fifty outlets write about it. Every news feed shows fifty headlines and leaves you to work out that they are one event. More importantly, it leaves you to work out whether anyone actually confirmed it, or whether fifty outlets are repeating one unchecked wire report. That second question is the one that matters, and no news aggregator answers it.",
      "hasCaseStudy": true,
      "tradeoffCount": 7,
      "tradeoffs": [
        {
          "decision": "What counts as confirmation",
          "chose": "Different publishers, worked out with the Public Suffix List",
          "rejected": "Counting articles or feeds",
          "why": "One newsroom filing five updates is one source. Counting feeds would let a publisher confirm its own story, which would make the only number the product offers meaningless."
        },
        {
          "decision": "How editions work",
          "chose": "Three orderings of all the stories",
          "rejected": "Three feeds split by a fixed source count",
          "why": "The split put about 95% of stories on one page and left the other two almost always empty. Ordering the same stories means no edition can run dry, and confirmation becomes a signal on every card instead of a separate page."
        },
        {
          "decision": "Grouping articles into stories",
          "chose": "By meaning (cosine similarity ≥ 0.80, calibrated)",
          "rejected": "Matching exact headlines",
          "why": "Three outlets write three different headlines for one event. Exact matching would leave every article on its own forever, which is the very problem the product exists to fix. The threshold sits above every 'different event' pair in the labelled set, because missing a merge is better than inventing one."
        },
        {
          "decision": "A story's main topic",
          "chose": "One vote per publisher, recounted as coverage arrives",
          "rejected": "Every tag from every article",
          "why": "A list of every tag only grows, so stories drifted into every topic any outlet used, and the 'main' topic was whichever row the database returned first. One vote per publisher also means one outlet filing five pieces can't outvote four other newsrooms."
        },
        {
          "decision": "How pages are fetched",
          "chose": "Page by time first seen, then ID (first_seen_at, id)",
          "rejected": "Page by momentum or ranking score",
          "why": "Only values that never change can be paged reliably. Grouping rewrites ranking scores, so paging by them repeats and skips rows. The ranked editions are fixed-size snapshots instead."
        },
        {
          "decision": "Where heavy batch work runs",
          "chose": "GitHub Actions runners",
          "rejected": "The web server, on a timer",
          "why": "Creating embeddings needs a lot of memory for a few minutes, and serving pages needs a little all the time. The runner has 7GB free and the API host 512MB. Doing batch work on the web server gets that backwards and blocks requests while it runs."
        },
        {
          "decision": "How articles are shown",
          "chose": "A ~40-word excerpt and a link to the original",
          "rejected": "Showing the full article",
          "why": "This is an aggregator, not a publisher. Linking out is the obligation that comes with using someone else's work. The same rule keeps publisher videos as links to the outlet rather than a player here."
        }
      ],
      "links": {
        "github": "https://github.com/emmanuelrichard01/ULTRA-NEWS",
        "live": "https://ultra-news.vercel.app/"
      }
    },
    {
      "id": "caritas-scholar",
      "title": "CARITAS AI Scholar",
      "subtitle": "Intelligent Academic Platform",
      "tier": "production",
      "category": "AI / RAG",
      "timeline": "2025",
      "status": "live",
      "stack": [
        "TypeScript",
        "React",
        "Vite",
        "Supabase",
        "Deno",
        "PostgreSQL",
        "Gemini",
        "Tailwind"
      ],
      "metrics": [
        "Workflows: 7",
        "Edge Functions: 6",
        "Access: Row-level"
      ],
      "summary": "Students juggle lots of single-purpose tools: one for notes, another for flashcards, a calculator for GPA, a separate search for papers. None of them share anything. Ask a question on Monday and there's no record of it on Friday. For about three thousand students at Caritas University, the problem was never any one tool. It was that none of them knew about each other.",
      "hasCaseStudy": true,
      "tradeoffCount": 4,
      "tradeoffs": [
        {
          "decision": "Where AI calls run",
          "chose": "Deno edge functions on the server",
          "rejected": "Calling the AI straight from the browser",
          "why": "Calling from the browser means sending an AI provider key to every visitor. The edge function keeps the key on the server and gives one place to check logins and route requests."
        },
        {
          "decision": "AI provider",
          "chose": "A router across several providers (Gemini, OpenRouter, OpenAI)",
          "rejected": "One fixed provider",
          "why": "Providers limit usage, retire models and go down. Putting them behind one edge function makes switching provider a setting instead of a rewrite."
        },
        {
          "decision": "Where user roles are stored",
          "chose": "A separate user_roles table, checked by a protected has_role() function (SECURITY DEFINER)",
          "rejected": "A role column on the profiles table",
          "why": "Users can edit their own profile row. A role stored there is a way to give yourself admin rights, waiting to be found."
        },
        {
          "decision": "Broken AI output",
          "chose": "Repair it with jsonrepair",
          "rejected": "Reject it and ask again",
          "why": "AI models produce almost-valid JSON often enough that asking again is slower and costs more than fixing it. Asking again is still the fallback when a repair fails."
        }
      ],
      "links": {
        "github": "https://github.com/emmanuelrichard01/caritas-ai-scholar",
        "live": "https://caritas-ai-scholar.vercel.app/"
      }
    },
    {
      "id": "global-rate-limiter",
      "title": "Global Rate Limiter as a Service",
      "subtitle": "High-availability API quota management",
      "tier": "system",
      "category": "API Infrastructure",
      "timeline": "2026",
      "status": "private build",
      "stack": [
        "TypeScript",
        "Node.js",
        "Express",
        "Redis",
        "Lua",
        "PostgreSQL",
        "nginx",
        "Docker"
      ],
      "metrics": [
        "Admission: Exactly 50/300",
        "Check Latency: p99 <15ms",
        "Tests: 36 / 7 suites"
      ],
      "summary": "Calls to outside APIs with a quota, such as banking, logistics or AI providers, are counted by the provider, not by you, and going over costs real money. The hard part is that the limit has to hold across many identical servers. If each one keeps its own count, together they go over. This is the reverse of the usual problem. Tools like Kong and Envoy protect your API from people calling in. Here the job is to keep your own outgoing calls inside someone else's budget, and a limiter that blocks everything when it breaks would take the whole fleet down with it.",
      "hasCaseStudy": true,
      "tradeoffCount": 5,
      "tradeoffs": [
        {
          "decision": "How requests are counted",
          "chose": "Token bucket",
          "rejected": "Fixed window, sliding window log, leaky bucket",
          "why": "A fixed window lets 200 requests through across the edge of two windows when the limit is 100 per window, which rules it out when the whole job is protecting a hard quota. A sliding window log is accurate but stores the time of every request, so memory grows with traffic instead of with the number of clients. A leaky bucket smooths traffic to a steady rate, but the need here is a budget that allows short bursts. A token bucket is two numbers per client and matches the need exactly."
        },
        {
          "decision": "Making check-and-spend one step",
          "chose": "One Lua script, run with EVALSHA",
          "rejected": "MULTI/EXEC with WATCH, or a distributed lock",
          "why": "WATCH works by retrying when something changed underneath it, so it gets slower exactly when traffic is heaviest. Redlock's correctness is disputed even among Redis users, and it costs an extra round trip for what is one key. A Lua script is all-or-nothing by design, which is why the race test can check for an exact number instead of a rough one."
        },
        {
          "decision": "What happens when Redis is down",
          "chose": "Fail open, but with limits: each server enforces the real limit on its own",
          "rejected": "Block everything, or let everything through",
          "why": "Blocking everything breaks the rule that traffic must never be fully stopped. Letting everything through keeps traffic moving but abandons the point of the system, which is avoiding penalties for going over quota, and an outage is the worst time to stop counting. Local limits mean the worst case is N times the intended rate across N servers. That is too much, on purpose, but it has a ceiling."
        },
        {
          "decision": "How logs are moved",
          "chose": "Redis Streams with consumer groups",
          "rejected": "An in-memory queue, or Kafka",
          "why": "The first version used an in-memory queue and lost a batch when the process crashed. That was caught in review and replaced, not designed right the first time. Streams survive crashes, deliver each entry at least once, let several workers share the load, and can reclaim entries a dead worker never confirmed (XAUTOCLAIM), all without adding a new system to a 2.5-day build."
        },
        {
          "decision": "Keeping settings up to date",
          "chose": "An LRU cache, instant updates through pub/sub, and a full check every 60 seconds",
          "rejected": "Re-reading the whole clients table every few seconds",
          "why": "Re-reading every row every few seconds keeps every client in memory whether it is active or not. Pub/sub on its own isn't enough either. Redis pub/sub doesn't retry, so a brief disconnect loses that message for good, and a cache that can go silently and permanently out of date is worse than one that is sometimes 60 seconds behind. This was a real bug: a plan changed directly in SQL never reached clients already in the cache, so the 60-second check went back in as a safety net."
        }
      ],
      "links": {}
    },
    {
      "id": "cloud-bill-hunter",
      "title": "Cloud Bill Hunter",
      "subtitle": "FinOps Intelligence Platform",
      "tier": "system",
      "category": "FinOps",
      "timeline": "2025",
      "status": "source available",
      "stack": [
        "Python",
        "FastAPI",
        "React",
        "Airflow",
        "DuckDB",
        "Terraform",
        "Pandera",
        "Docker"
      ],
      "metrics": [
        "Detection: Z-score",
        "Contracts: Pandera",
        "Storage: DuckDB"
      ],
      "summary": "Cloud waste hides in plain sight: resources nobody uses, billing every hour. Normal cost reports show the total but not which items are the forgotten ones. And the obvious check, 'usage is zero', misses everything that is nearly idle or has just started spiking.",
      "hasCaseStudy": true,
      "tradeoffCount": 3,
      "tradeoffs": [
        {
          "decision": "Running the pipeline",
          "chose": "Apache Airflow",
          "rejected": "Scripts that watch a folder",
          "why": "Retries, deadline monitoring and run history come built in. The folder-watching scripts had no answer for a run that failed halfway."
        },
        {
          "decision": "Dashboard",
          "chose": "React + Vite with Recharts",
          "rejected": "Streamlit",
          "why": "Streamlit was quick to set up but limited both what you could do and how it looked. Rebuilding it gave full control of both."
        },
        {
          "decision": "Storage engine",
          "chose": "DuckDB",
          "rejected": "A hosted data warehouse",
          "why": "A built-in analytics engine is fast enough for cost reports of this size, with nothing to run or pay for."
        }
      ],
      "links": {
        "github": "https://github.com/emmanuelrichard01/cloud-bill-hunter"
      }
    },
    {
      "id": "crypto-pipeline",
      "title": "Crypto Data Pipeline",
      "subtitle": "Market Analytics Engine",
      "tier": "system",
      "category": "Data Pipeline",
      "timeline": "2025",
      "status": "source available",
      "stack": [
        "Python",
        "dbt",
        "PostgreSQL",
        "Redis",
        "Docker",
        "Streamlit",
        "Grafana"
      ],
      "metrics": [
        "Cadence: Hourly",
        "Freshness SLA: 2h alert",
        "Coverage: 80%+"
      ],
      "summary": "Market data is easy to fetch and hard to trust. A public API will happily give you a price. It won't tell you that the last three hours are missing, that a price jumped 40% because of a bad data point rather than the market, or that your dashboard is quietly showing yesterday's numbers. A chart built straight on an API call inherits all of those problems without telling you.",
      "hasCaseStudy": true,
      "tradeoffCount": 3,
      "tradeoffs": [
        {
          "decision": "Where data quality is checked",
          "chose": "dbt schema tests in the warehouse",
          "rejected": "Checks inside the fetching script",
          "why": "Checks in the script only cover what that script did. Tests attached to the models check the data on every run, whatever produced it."
        },
        {
          "decision": "Dashboards",
          "chose": "Streamlit for analysis, Grafana for operations",
          "rejected": "One tool for both",
          "why": "Market trends and pipeline health are for different people and need different refresh rates. Putting them on one screen makes both worse."
        },
        {
          "decision": "How often to fetch",
          "chose": "Once an hour, in batches",
          "rejected": "Live streaming",
          "why": "The questions being asked are about trends, not second-by-second ticks. Hourly stays well inside the free API limits and avoids a whole layer of streaming infrastructure that would add nothing here."
        }
      ],
      "links": {
        "github": "https://github.com/emmanuelrichard01/crypto-data-pipeline"
      }
    },
    {
      "id": "evanty",
      "title": "Evanty",
      "subtitle": "Event Management Platform",
      "tier": "system",
      "category": "Full-Stack",
      "timeline": "2025",
      "status": "live",
      "stack": [
        "Next.js",
        "TypeScript",
        "MongoDB",
        "Stripe",
        "Clerk"
      ],
      "metrics": [
        "Payments: Stripe",
        "Auth: Clerk"
      ],
      "summary": "An events platform built with Next.js 14: create and browse events, sign in with Clerk, and pay with Stripe checkout. Data lives in MongoDB, forms are validated with Zod, and webhooks keep user and payment records in sync.",
      "hasCaseStudy": false,
      "tradeoffCount": 0,
      "tradeoffs": [],
      "links": {
        "github": "https://github.com/emmanuelrichard01/Evanty",
        "live": "https://evanty.vercel.app/"
      }
    },
    {
      "id": "cbn-data-residency",
      "title": "CBN Data Residency Migration",
      "subtitle": "Reference Architecture for Local Payment Data Storage",
      "tier": "design",
      "category": "Regulatory Architecture",
      "timeline": "2026",
      "status": "design-stage, not built",
      "stack": [],
      "metrics": [
        "Compliance Deadline: Jan 2027"
      ],
      "summary": "A plan for moving Nigerian payment data onto storage inside Nigeria before the Central Bank of Nigeria's January 2027 deadline, set out in Circular PSS/DIR/PUB/CIR/001/004. It maps out the migration steps, where the line around local data sits, and which kinds of data the circular actually covers.",
      "hasCaseStudy": false,
      "tradeoffCount": 0,
      "tradeoffs": [],
      "links": {}
    },
    {
      "id": "smart-meter-telemetry",
      "title": "Smart Meter & Inverter Telemetry",
      "subtitle": "Distributed IoT Telemetry Platform",
      "tier": "design",
      "category": "Streaming Architecture",
      "timeline": "2026",
      "status": "design-stage, not built",
      "stack": [
        "Apache Flink",
        "Apache Iceberg",
        "TimescaleDB"
      ],
      "metrics": [],
      "summary": "A design, not yet built, for collecting live readings from smart meters and solar inverters spread across many sites. Flink processes the stream, Iceberg stores the history as tables, and TimescaleDB serves the time-series data.",
      "hasCaseStudy": false,
      "tradeoffCount": 0,
      "tradeoffs": [],
      "links": {}
    }
  ],
  "experience": [
    {
      "id": "mercor",
      "company": "Mercor",
      "role": "Software Engineer, AI Benchmarking",
      "type": "Part-time",
      "period": "Jul – Sep 2026",
      "summary": "Built Codebase Atlas Q&A, a benchmark for Mercor's reinforcement learning (RL) platform that tests how well leading AI models understand whole codebases and reason about how they are designed.",
      "stack": [
        "Python",
        "Docker",
        "Bash",
        "RewardKit",
        "LLM Evaluation"
      ]
    },
    {
      "id": "medvax",
      "company": "MedVax Health",
      "role": "Software & Data Engineer",
      "type": "Contract",
      "period": "Jan – Feb 2026",
      "summary": "Designed a secure online prescription portal for doctors and patients on a live health platform, covering prescriptions, sign-in and payments.",
      "stack": [
        "Python",
        "FastAPI",
        "NestJS",
        "Prisma",
        "TypeScript",
        "PostgreSQL",
        "Docker"
      ]
    },
    {
      "id": "setraco",
      "company": "SETRACO Nigeria",
      "role": "Data Operations & Systems Engineer",
      "type": "Full-time",
      "period": "Mar – Oct 2024",
      "summary": "Replaced a construction firm's manual Excel reporting with central, shared reports, cutting reporting effort by ~40% and giving every site the same way of tracking work.",
      "stack": [
        "Python",
        "SQL",
        "React",
        "Next.js",
        "PostgreSQL",
        "Data Analysis"
      ],
      "note": "Completed alongside the final year of the B.Eng."
    },
    {
      "id": "freelance",
      "company": "Independent Consultant",
      "role": "Freelance Software Engineer",
      "type": "Freelance",
      "period": "Oct 2020 – Mar 2024",
      "summary": "Built websites and data tools for independent and small-business clients, running each project from proposal to delivery, all while studying full-time for an engineering degree.",
      "stack": [
        "Python",
        "TypeScript",
        "React",
        "SQL",
        "Tailwind CSS"
      ],
      "note": "Concurrent with the B.Eng. at Caritas University."
    },
    {
      "id": "tac-africa",
      "company": "TAC AFRICA",
      "role": "Full Stack Engineer",
      "type": "Part-time",
      "period": "Aug 2019 – Aug 2020",
      "summary": "Built and maintained web apps used by 50,000+ people. Made the backend APIs and SQL queries ~45% faster to respond by digging through logs, finding the slow spots and tuning the database.",
      "stack": [
        "Python",
        "JavaScript",
        "SQL",
        "REST APIs",
        "PostgreSQL"
      ],
      "note": "Concurrent with the AfriHUB ICT role below."
    },
    {
      "id": "afrihub",
      "company": "AfriHUB ICT",
      "role": "Software Engineer",
      "type": "Part-time",
      "period": "Oct 2018 – Oct 2020",
      "summary": "Designed and built software for schools and businesses using modern web tools, and helped deploy, connect and maintain their larger business systems.",
      "stack": [
        "Python",
        "SQL",
        "JavaScript",
        "MySQL",
        "HTML/CSS"
      ],
      "note": "Done alongside the National Innovative Diploma programme."
    },
    {
      "id": "notap",
      "company": "NOTAP",
      "role": "Junior IT Consultant",
      "type": "Internship",
      "period": "Oct 2018 – Mar 2019",
      "summary": "IT and technical consulting at the National Office for Technology Acquisition and Promotion: planning IT set-ups for small businesses, setting up networks, and supporting the staff who used them.",
      "stack": [
        "PHP",
        "HTML/CSS",
        "Networking"
      ],
      "note": "Concurrent with the first months at AfriHUB ICT."
    }
  ]
};

export default CONTEXT;
